### PR TITLE
Adds banners from DevFest Nordeste 2014 (Brazil)

### PR DESCRIPTION
**Pull request by erickmendonca**
These are kinda large files, I'm not sure if store them directly on the Git repo is a good idea.

### CODE REVIEW

**Comment by erickmendonca** [comment]
Files created by @faeliaso

**Comment by tasomaniac** [comment]
I think png files are not necessary because they cannot be reused by other people. They cannot be easily edited. 

Other then that, I think it is a really good contribution

**Comment by erickmendonca** [comment]
The png files were included just for previewing, but we can remove :)

**Comment by tasomaniac** [comment]
Oh pardon me. You are right. Sorry

**Pull request merged**
